### ISSUE TITLE
Production ready?

### ISSUE THREAD

**Issue by wilddev65** [akamai/PowerShell#2]
Hi,

I just noticed this project. We currently use v1 for integration between Venafi and Akamai to provision certificates and from looking at what you've done so far I suspect that this will align much better with what we are currently doing. I was wondering if you regard this as being production ready for customers or if it's still a work in progress. I would love to refactor our current driver to using this code and simplify the integration along with better handle checking of the current status of the change requests in Akamai.

Thank you
Chris

**Comment by stuart-macleod-akamai** [comment]
Hi Chris.

Sorry, your query fell between the cracks. Yes, this is definitely production-ready, so we'd be very pleased if you gave it a try. Any issues you find, please raise here and we'll get them fixed asap.

Thanks
